package com.example.salesagent.history;

import com.example.salesagent.model.ChatResponse;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.mybatis.spring.annotation.MapperScan;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest(classes = PgChatHistoryStoreTest.TestApp.class, properties = {
        "spring.profiles.active=app",
        "spring.datasource.url=jdbc:h2:mem:chat_history;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
        "spring.datasource.username=sa", "spring.datasource.password=",
        "spring.flyway.enabled=false"
})
/** 验证会话排序、最近问答和事务回滚。 */
class PgChatHistoryStoreTest {
    @SpringBootConfiguration @EnableAutoConfiguration
    @MapperScan("com.example.salesagent.history")
    @Import(PgChatHistoryStore.class)
    static class TestApp {}

    @Autowired JdbcTemplate jdbc;
    @Autowired PgChatHistoryStore store;

    @BeforeEach void reset() {
        jdbc.execute("DROP TABLE IF EXISTS chat_turn");
        jdbc.execute("DROP TABLE IF EXISTS chat_session");
        jdbc.execute("CREATE TABLE chat_session (id VARCHAR(64) PRIMARY KEY, title VARCHAR(120) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL)");
        jdbc.execute("CREATE TABLE chat_turn (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, session_id VARCHAR(64) NOT NULL REFERENCES chat_session(id), question TEXT NOT NULL, answer TEXT NOT NULL, sources_json TEXT NOT NULL, steps_json TEXT NOT NULL, retrieval_ms BIGINT NOT NULL, total_ms BIGINT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL)");
    }

    /** 保存完整问答，并把最新会话排在前面。 */
    @Test void savesCompleteTurnsAndListsMostRecentlyUpdatedSessionFirst() {
        store.append("one", "第一个问题", new ChatResponse("one", "第一个回答", List.of("a.md"), List.of("检索"), 12, 30));
        store.append("two", "另一个问题", new ChatResponse("two", "另一个回答", List.of(), List.of(), 3, 9));
        store.append("one", "继续问", new ChatResponse("one", "继续答", List.of("b.md"), List.of("工具"), 4, 10));

        assertEquals(List.of("one", "two"), store.listSessions().stream().map(ChatSession::getId).toList());
        assertEquals("第一个问题", store.listSessions().get(0).getTitle());
        List<ChatTurn> turns = store.turns("one");
        assertEquals(List.of("第一个问题", "继续问"), turns.stream().map(ChatTurn::getQuestion).toList());
        assertEquals(List.of("a.md"), turns.get(0).getSources());
        assertEquals(List.of("工具"), turns.get(1).getSteps());
    }

    /** 只读取最近完整的几轮问答作为上下文。 */
    @Test void returnsOnlyLatestCompleteTurnsForAgentContext() {
        for (int i = 0; i < 12; i++) {
            store.append("one", "问题" + i, new ChatResponse("one", "回答" + i, List.of(), List.of(), 0, 1));
        }
        assertEquals(List.of("问题10", "问题11"), store.recentTurns("one", 2).stream().map(ChatTurn::getQuestion).toList());
        assertFalse(store.exists("missing"));
    }

    /** 问答保存失败时回滚新会话。 */
    @Test void rollsBackNewSessionWhenCompletedTurnCannotBeSaved() {
        assertThrows(Exception.class, () -> store.append("failed", "问题",
                new ChatResponse("failed", null, List.of(), List.of(), 0, 1)));
        assertFalse(store.exists("failed"));
    }

    /** 重复提问仍保存为不同轮次。 */
    @Test void savesRepeatedQuestionsAsSeparateTurns() {
        ChatResponse answer = new ChatResponse("one", "回答", List.of(), List.of(), 0, 1);
        store.append("one", "问题", answer);
        store.append("one", "问题", answer);
        assertEquals(2, store.turns("one").size());
        assertEquals(List.of("回答", "回答"), store.turns("one").stream().map(ChatTurn::getAnswer).toList());
    }
}
