-- 会话保存标题和最近活跃时间，供历史列表展示。
CREATE TABLE chat_session (
    id varchar(64) PRIMARY KEY,
    title varchar(120) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

-- 每条记录是一轮完整问答，来源和步骤以 JSON 文本保存。
CREATE TABLE chat_turn (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id varchar(64) NOT NULL REFERENCES chat_session(id),
    request_id varchar(64) NOT NULL,
    question text NOT NULL,
    answer text NOT NULL,
    sources_json text NOT NULL,
    steps_json text NOT NULL,
    retrieval_ms bigint NOT NULL,
    total_ms bigint NOT NULL,
    created_at timestamp with time zone NOT NULL
);

-- 历史列表按更新时间排序，轮次按会话和编号读取。
CREATE INDEX chat_session_recent_idx ON chat_session (updated_at DESC, id DESC);
CREATE INDEX chat_turn_session_idx ON chat_turn (session_id, id);
CREATE UNIQUE INDEX chat_turn_request_idx ON chat_turn (session_id, request_id);
