CREATE TABLE chat_session (
    id varchar(64) PRIMARY KEY,
    title varchar(120) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE chat_turn (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id varchar(64) NOT NULL REFERENCES chat_session(id),
    request_id varchar(64) NOT NULL,
    question text NOT NULL,
    answer text NOT NULL,
    sources_json text NOT NULL,
    steps_json text NOT NULL,
    retrieval_ms bigint NOT NULL,
    total_ms bigint NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE INDEX chat_session_recent_idx ON chat_session (updated_at DESC, id DESC);
CREATE INDEX chat_turn_session_idx ON chat_turn (session_id, id);
CREATE UNIQUE INDEX chat_turn_request_idx ON chat_turn (session_id, request_id);
